source 'https://rubygems.org'

gem 'rails', '3.2.13'

gem 'pg'

group :assets do
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

group :development, :test do
  gem 'rspec-rails'
end

group :test do
  gem 'capybara'
  gem 'selenium-webdriver'
  gem 'database_cleaner'
end
